"""
Trading Performance Analyzer
============================
Reads a trade history CSV and produces a weekly performance review:

  1. Overall statistics (win rate, expectancy, total P&L, etc.)
  2. Performance by setup type
  3. Performance by time of day (hourly blocks)
  4. Performance by day of week
  5. Pattern detection (best/worst hour, best/worst setup, consistent losers)
  6. Written summary in plain English
  7. Data-driven recommendations

Usage:
    python reporting/analyze_trades.py reports/04-19-2026_04-25-2026_tradelog.csv
    python reporting/analyze_trades.py reports/04-19-2026_04-25-2026_tradelog.csv --output reports/analysis.txt

Required CSV columns (case-insensitive, flexible naming):
    Symbol, Entry Date, Entry Time, Entry Price, Exit Date, Exit Time,
    Exit Price, Shares, P&L, Setup Type (or Strategy)

Generated by Opus 4, integrated and fixed by Claude Sonnet.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from datetime import time as dtime
from pathlib import Path

import pandas as pd
import os

# Add project root to Python path and change working directory to root.
# This allows scripts in Scripts/ to import from data/, core/, strategies/ etc.
_project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)
os.chdir(_project_root)


# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------

# Time-of-day buckets covering full 24 hours so crypto trades are never excluded.
# Stock market hours (09:30-16:00) broken into 1-hour blocks.
# Pre-market, after-hours, and overnight crypto get their own buckets.
TIME_BLOCKS: list[tuple[str, dtime, dtime]] = [
    ("00:00-09:30", dtime(0,  0),  dtime(9,  30)),   # Overnight / pre-market crypto
    ("09:30-10:30", dtime(9,  30), dtime(10, 30)),   # Stock open (noisy)
    ("10:30-11:30", dtime(10, 30), dtime(11, 30)),
    ("11:30-12:30", dtime(11, 30), dtime(12, 30)),
    ("12:30-13:30", dtime(12, 30), dtime(13, 30)),
    ("13:30-14:30", dtime(13, 30), dtime(14, 30)),
    ("14:30-16:00", dtime(14, 30), dtime(16, 0)),    # Stock close
    ("16:00-24:00", dtime(16, 0),  dtime(23, 59)),   # After-hours / evening crypto
]

# Full week including weekend crypto trading
DAY_ORDER = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]

# Map common column-name variations -> canonical name.
COLUMN_ALIASES: dict[str, str] = {
    "symbol": "symbol",
    "ticker": "symbol",
    "entry date": "entry_date",
    "entry_date": "entry_date",
    "entry time": "entry_time",
    "entry_time": "entry_time",
    "entry price": "entry_price",
    "entry_price": "entry_price",
    "exit date": "exit_date",
    "exit_date": "exit_date",
    "exit time": "exit_time",
    "exit_time": "exit_time",
    "exit price": "exit_price",
    "exit_price": "exit_price",
    "shares": "shares",
    "quantity": "shares",
    "qty": "shares",
    "p&l": "pnl",
    "pnl": "pnl",
    "profit": "pnl",
    "profit/loss": "pnl",
    # 'Strategy' from our weekly_tradelog.py maps to 'setup_type'
    "setup type": "setup_type",
    "setup_type": "setup_type",
    "setup": "setup_type",
    "strategy": "setup_type",
    "strategy_name": "setup_type",
}

REQUIRED_COLUMNS = {
    "symbol", "entry_date", "entry_time", "entry_price",
    "exit_date", "exit_time", "exit_price", "shares", "pnl", "setup_type",
}


# -----------------------------------------------------------------------------
# Data loading
# -----------------------------------------------------------------------------

def load_trades(csv_path: Path) -> pd.DataFrame:
    """Load the CSV, normalize column names, parse types, and validate."""
    if not csv_path.exists():
        raise FileNotFoundError(f"CSV file not found: {csv_path}")

    df = pd.read_csv(csv_path)

    # Normalize column names first
    df.columns = [c.strip().lower() for c in df.columns]

    # Stop at summary footer rows
    if "symbol" in df.columns:
        df = df[df["symbol"].notna() & (df["symbol"].astype(str).str.strip() != "")]
        df = df[~df["symbol"].astype(str).str.startswith("---")]
        # Also drop rows where symbol looks like a summary label
        summary_labels = {"total trades", "winning trades", "losing trades",
                         "win rate", "total p&l", "period", "generated"}
        df = df[~df["symbol"].astype(str).str.lower().isin(summary_labels)]

    # Map aliases
    df = df.rename(columns={c: COLUMN_ALIASES.get(c, c) for c in df.columns})

    # Validate required columns
    missing = REQUIRED_COLUMNS - set(df.columns)
    if missing:
        raise ValueError(
            f"CSV is missing required columns: {sorted(missing)}.\n"
            f"Found columns: {sorted(df.columns)}"
        )

    # Parse entry_time into time-of-day
    df["entry_time_parsed"] = pd.to_datetime(
        df["entry_time"].astype(str), errors="coerce", format="mixed"
    ).dt.time

    # Parse entry_date for day-of-week
    df["entry_date_parsed"] = pd.to_datetime(
        df["entry_date"].astype(str), errors="coerce", format="mixed"
    )

    # Coerce P&L — strip $, commas, + signs
    df["pnl"] = pd.to_numeric(
        df["pnl"].astype(str).str.replace(r"[$,+]", "", regex=True),
        errors="coerce",
    )
    df["shares"] = pd.to_numeric(df["shares"], errors="coerce")

    # Normalize setup_type
    df["setup_type"] = df["setup_type"].astype(str).str.strip()

    # Drop rows that failed to parse
    bad = df[df["pnl"].isna() | df["entry_time_parsed"].isna() | df["entry_date_parsed"].isna()]
    if len(bad):
        print(f"WARNING: Dropped {len(bad)} row(s) with unparseable date/time/PnL.",
              file=sys.stderr)
        df = df.drop(bad.index)

    if df.empty:
        raise ValueError("No valid trades remain after parsing. Check CSV format.")

    return df.reset_index(drop=True)


# -----------------------------------------------------------------------------
# Core statistics
# -----------------------------------------------------------------------------

@dataclass
class Stats:
    trades: int
    winners: int
    losers: int
    win_rate: float
    avg_win: float
    avg_loss: float
    expectancy: float
    largest_win: float
    largest_loss: float
    total_pnl: float
    avg_pnl: float

    def as_dict(self) -> dict:
        return {
            "Trades": self.trades,
            "Winners": self.winners,
            "Losers": self.losers,
            "Win Rate %": round(self.win_rate, 2),
            "Avg Win": round(self.avg_win, 2),
            "Avg Loss": round(self.avg_loss, 2),
            "Expectancy": round(self.expectancy, 2),
            "Largest Win": round(self.largest_win, 2),
            "Largest Loss": round(self.largest_loss, 2),
            "Total P&L": round(self.total_pnl, 2),
            "Avg P&L": round(self.avg_pnl, 2),
        }


def compute_stats(pnl_series: pd.Series) -> Stats:
    trades = len(pnl_series)
    if trades == 0:
        return Stats(0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)

    wins   = pnl_series[pnl_series > 0]
    losses = pnl_series[pnl_series < 0]

    winners = len(wins)
    losers  = len(losses)
    decided = winners + losers

    win_rate  = (winners / decided * 100) if decided > 0 else 0.0
    loss_rate = (losers  / decided)       if decided > 0 else 0.0

    avg_win    = wins.mean()   if winners > 0 else 0.0
    avg_loss   = losses.mean() if losers  > 0 else 0.0
    expectancy = (win_rate / 100) * avg_win + loss_rate * avg_loss

    return Stats(
        trades=trades, winners=winners, losers=losers,
        win_rate=win_rate, avg_win=float(avg_win), avg_loss=float(avg_loss),
        expectancy=float(expectancy),
        largest_win=float(pnl_series.max()),
        largest_loss=float(pnl_series.min()),
        total_pnl=float(pnl_series.sum()),
        avg_pnl=float(pnl_series.mean()),
    )


# -----------------------------------------------------------------------------
# Bucketing helpers
# -----------------------------------------------------------------------------

def assign_time_block(t: dtime | None) -> str | None:
    """
    Map a time-of-day to a named block.
    Now covers full 24 hours so crypto trades are never excluded.
    Midnight (00:00:00) handled as start of overnight block.
    """
    if t is None or pd.isna(t):
        return None
    for label, start, end in TIME_BLOCKS:
        # Handle the 16:00-24:00 block which ends at 23:59
        if label == "16:00-24:00":
            if t >= start:
                return label
        elif start <= t < end:
            return label
    return "00:00-09:30"  # Catch midnight exactly


def group_stats(df: pd.DataFrame, group_col: str,
               order: list[str] | None = None) -> pd.DataFrame:
    rows = []
    for name, sub in df.groupby(group_col, dropna=False):
        if pd.isna(name):
            continue
        row = {group_col: name, **compute_stats(sub["pnl"]).as_dict()}
        rows.append(row)

    if not rows:
        return pd.DataFrame()

    out = pd.DataFrame(rows)
    if order:
        out[group_col] = pd.Categorical(out[group_col], categories=order, ordered=True)
        out = out.sort_values(group_col).reset_index(drop=True)
    else:
        out = out.sort_values("Total P&L", ascending=False).reset_index(drop=True)
    return out


# -----------------------------------------------------------------------------
# Pattern detection
# -----------------------------------------------------------------------------

def detect_patterns(by_hour: pd.DataFrame, by_setup: pd.DataFrame,
                    min_trades: int = 3) -> dict[str, str]:
    findings: dict[str, str] = {}

    def _rank_by(df, key_col, metric, label_prefix):
        if df.empty:
            return None, None
        qualified = df[df["Trades"] >= min_trades]
        if qualified.empty:
            return (f"[{label_prefix}] Not enough data: no bucket has >= "
                    f"{min_trades} trades.", None)
        best  = qualified.loc[qualified[metric].idxmax()]
        worst = qualified.loc[qualified[metric].idxmin()]
        return best, worst

    res = _rank_by(by_hour, "time_block", "Total P&L", "Hourly")
    if isinstance(res, tuple) and res[0] is not None and not isinstance(res[0], str):
        best_hour, worst_hour = res
        findings["Best Hour"] = (
            f"{best_hour['time_block']}  "
            f"(Total P&L: ${best_hour['Total P&L']:,.2f}, "
            f"Win Rate: {best_hour['Win Rate %']}%, "
            f"Trades: {best_hour['Trades']})"
        )
        if best_hour["time_block"] != worst_hour["time_block"]:
            findings["Worst Hour"] = (
                f"{worst_hour['time_block']}  "
                f"(Total P&L: ${worst_hour['Total P&L']:,.2f}, "
                f"Win Rate: {worst_hour['Win Rate %']}%, "
                f"Trades: {worst_hour['Trades']})"
            )
    elif isinstance(res, tuple) and isinstance(res[0], str):
        findings["Hourly Note"] = res[0]

    res = _rank_by(by_setup, "setup_type", "Total P&L", "Setup")
    if isinstance(res, tuple) and res[0] is not None and not isinstance(res[0], str):
        best_setup, worst_setup = res
        findings["Best Setup"] = (
            f"{best_setup['setup_type']}  "
            f"(Total P&L: ${best_setup['Total P&L']:,.2f}, "
            f"Win Rate: {best_setup['Win Rate %']}%, "
            f"Expectancy: ${best_setup['Expectancy']:,.2f}, "
            f"Trades: {best_setup['Trades']})"
        )
        if best_setup["setup_type"] != worst_setup["setup_type"]:
            findings["Worst Setup"] = (
                f"{worst_setup['setup_type']}  "
                f"(Total P&L: ${worst_setup['Total P&L']:,.2f}, "
                f"Win Rate: {worst_setup['Win Rate %']}%, "
                f"Expectancy: ${worst_setup['Expectancy']:,.2f}, "
                f"Trades: {worst_setup['Trades']})"
            )
    elif isinstance(res, tuple) and isinstance(res[0], str):
        findings["Setup Note"] = res[0]

    losing_buckets = []
    if not by_hour.empty:
        candidates = by_hour[
            (by_hour["Trades"] >= min_trades)
            & (by_hour["Total P&L"] < 0)
            & (by_hour["Win Rate %"] < 40)
        ]
        for _, row in candidates.iterrows():
            losing_buckets.append(
                f"{row['time_block']}: "
                f"${row['Total P&L']:,.2f} over {row['Trades']} trades "
                f"({row['Win Rate %']}% win rate)"
            )
    findings["Consistent Loss Periods"] = (
        "; ".join(losing_buckets) if losing_buckets
        else "None flagged (no qualifying bucket had both negative P&L and <40% win rate)."
    )

    return findings


# -----------------------------------------------------------------------------
# Written summary & recommendations
# -----------------------------------------------------------------------------

def generate_summary(overall: Stats, by_setup: pd.DataFrame, by_hour: pd.DataFrame,
                     by_dow: pd.DataFrame, findings: dict[str, str],
                     min_trades: int = 3) -> tuple[str, list[str]]:
    summary_lines: list[str] = []
    recs: list[str] = []

    if overall.trades == 0:
        return "No trades to analyze.", []

    pnl_sign = "profit" if overall.total_pnl > 0 else "loss" if overall.total_pnl < 0 else "breakeven"
    summary_lines.append(
        f"Across {overall.trades} trades you produced a total {pnl_sign} of "
        f"${overall.total_pnl:,.2f}, with a {overall.win_rate:.1f}% win rate "
        f"and an expectancy of ${overall.expectancy:,.2f} per trade."
    )

    if overall.avg_loss < 0:
        r_ratio = abs(overall.avg_win / overall.avg_loss)
        summary_lines.append(
            f"Your average winner is ${overall.avg_win:,.2f} and average loser is "
            f"${overall.avg_loss:,.2f}, a {r_ratio:.2f}:1 win/loss ratio."
        )
        if r_ratio < 1.0 and overall.win_rate < 60:
            recs.append(
                f"Your win/loss ratio is {r_ratio:.2f}:1 and win rate is "
                f"{overall.win_rate:.1f}%. You need EITHER a higher win rate "
                "OR larger winners relative to losers. Consider tightening "
                "stops, letting winners run longer, or being more selective on entries."
            )
        elif r_ratio >= 2.0:
            recs.append(
                f"Win/loss ratio of {r_ratio:.2f}:1 is strong -- your winners "
                "meaningfully outweigh losers. Protect this edge by not "
                "loosening stops or exiting winners too early."
            )

    if not by_setup.empty:
        qual_setups = by_setup[by_setup["Trades"] >= min_trades]
        if not qual_setups.empty:
            winning = qual_setups[qual_setups["Total P&L"] > 0]
            losing  = qual_setups[qual_setups["Total P&L"] < 0]
            win_verb  = "is" if len(winning) == 1 else "are"
            lose_verb = "is" if len(losing)  == 1 else "are"
            summary_lines.append(
                f"Of {len(qual_setups)} setup(s) with >= {min_trades} trades, "
                f"{len(winning)} {win_verb} profitable and {len(losing)} {lose_verb} "
                f"losing money."
            )
            if not losing.empty:
                worst = losing.loc[losing["Total P&L"].idxmin()]
                recs.append(
                    f"'{worst['setup_type']}' is costing you ${abs(worst['Total P&L']):,.2f} "
                    f"over {worst['Trades']} trades ({worst['Win Rate %']}% win rate). "
                    "Consider paper-trading this setup until it proves out, "
                    "or dropping it from your playbook entirely."
                )
            if not winning.empty:
                best = winning.loc[winning["Total P&L"].idxmax()]
                recs.append(
                    f"'{best['setup_type']}' is your highest-P&L setup "
                    f"(${best['Total P&L']:,.2f}, expectancy ${best['Expectancy']:,.2f}). "
                    "Consider allocating more size or more attention here."
                )

    if not by_hour.empty:
        qual_hours = by_hour[by_hour["Trades"] >= min_trades]
        if not qual_hours.empty:
            best_h  = qual_hours.loc[qual_hours["Total P&L"].idxmax()]
            worst_h = qual_hours.loc[qual_hours["Total P&L"].idxmin()]
            if best_h["time_block"] != worst_h["time_block"]:
                summary_lines.append(
                    f"Your best time block is {best_h['time_block']} "
                    f"(${best_h['Total P&L']:,.2f}) and worst is "
                    f"{worst_h['time_block']} (${worst_h['Total P&L']:,.2f})."
                )
                if worst_h["Total P&L"] < 0:
                    recs.append(
                        f"You're consistently losing during {worst_h['time_block']} "
                        f"(${worst_h['Total P&L']:,.2f} over {worst_h['Trades']} trades). "
                        "Consider sitting out this block, or at minimum cutting "
                        "size until you identify what's different."
                    )

    if not by_dow.empty:
        qual_dow    = by_dow[by_dow["Trades"] >= min_trades]
        losing_days = qual_dow[qual_dow["Total P&L"] < 0]
        if not losing_days.empty:
            day_list = ", ".join(losing_days["day_of_week"].astype(str).tolist())
            recs.append(
                f"Losing money on: {day_list}. Review whether these days have "
                "a pattern in strategy mix, market conditions, or session timing."
            )

    if overall.trades < 30:
        recs.append(
            f"Sample size is small ({overall.trades} trades). Treat these "
            "findings as directional hints, not conclusions -- revisit after "
            "30+ trades per bucket before making big rule changes."
        )

    return "\n".join(summary_lines), recs


def format_section(title: str) -> str:
    bar = "=" * 78
    return f"\n{bar}\n{title}\n{bar}"


def format_stats_block(stats: Stats) -> str:
    d = stats.as_dict()
    lines = []
    for k, v in d.items():
        if k in ("Trades", "Winners", "Losers", "Win Rate %"):
            lines.append(f"  {k:<18} {v:>12}")
        else:
            lines.append(f"  {k:<18} ${v:>11,.2f}")
    return "\n".join(lines)


def format_table(df: pd.DataFrame) -> str:
    if df.empty:
        return "  (no data)"
    return df.to_string(index=False)


def build_report(df: pd.DataFrame) -> str:
    out: list[str] = []

    # --- 1. Overall --------------------------------------------------------
    overall = compute_stats(df["pnl"])
    out.append(format_section("1. OVERALL STATISTICS"))
    out.append(format_stats_block(overall))

    # --- 2. By setup type --------------------------------------------------
    by_setup = group_stats(df, "setup_type")
    out.append(format_section("2. PERFORMANCE BY SETUP TYPE"))
    out.append(format_table(by_setup))

    # --- 3. By time of day (full 24h, no exclusions) -----------------------
    df = df.copy()
    df["time_block"] = df["entry_time_parsed"].apply(assign_time_block)
    by_hour = group_stats(df, "time_block",
                          order=[lbl for lbl, _, _ in TIME_BLOCKS])

    out.append(format_section("3. PERFORMANCE BY TIME OF DAY (ALL 24 HOURS)"))
    excluded = df["time_block"].isna().sum()
    if excluded > 0:
        out.append(f"  Note: {excluded} trade(s) with unparseable entry time excluded.\n")
    else:
        out.append("  All trades included (stocks + crypto, full 24h coverage).\n")
    out.append(format_table(by_hour))

    # --- 4. By day of week (full 7 days) -----------------------------------
    df["day_of_week"] = df["entry_date_parsed"].dt.day_name()
    by_dow = group_stats(df, "day_of_week", order=DAY_ORDER)
    out.append(format_section("4. PERFORMANCE BY DAY OF WEEK (ALL 7 DAYS)"))
    out.append(format_table(by_dow))

    # --- 5. Pattern detection ----------------------------------------------
    out.append(format_section("5. PATTERN DETECTION"))
    out.append("  (buckets with < 3 trades excluded to avoid small-sample noise)\n")
    findings = detect_patterns(by_hour, by_setup)
    if not findings:
        out.append("  No qualifying buckets for pattern detection.")
    else:
        for k, v in findings.items():
            out.append(f"  {k}: {v}")

    # --- 6. Written summary ------------------------------------------------
    summary, recs = generate_summary(overall, by_setup, by_hour, by_dow, findings)
    out.append(format_section("6. WRITTEN SUMMARY"))
    out.append(summary)

    # --- 7. Recommendations ------------------------------------------------
    out.append(format_section("7. RECOMMENDATIONS"))
    if not recs:
        out.append("  No specific recommendations generated from current data.")
    else:
        for i, rec in enumerate(recs, 1):
            lines = rec.split(". ")
            first = f"  {i}. {lines[0]}"
            rest  = [f"     {l}" for l in lines[1:]] if len(lines) > 1 else []
            out.append(first + ("." if not first.endswith(".") else ""))
            out.extend([r + ("." if not r.endswith(".") else "") for r in rest])
            out.append("")

    return "\n".join(out) + "\n"


# -----------------------------------------------------------------------------
# Entry point
# -----------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(description="Analyze trading performance from CSV.")
    parser.add_argument("csv_path", type=Path, help="Path to trades CSV file")
    parser.add_argument("--output", "-o", type=Path, default=None,
                        help="Optional path to write the report to (also prints to stdout)")
    args = parser.parse_args()

    try:
        df = load_trades(args.csv_path)
    except (FileNotFoundError, ValueError) as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1

    report = build_report(df)
    print(report)

    if args.output:
        args.output.write_text(report)
        print(f"Report saved to: {args.output}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
